### ISSUE TITLE
price update for coal burner is not working 

### ISSUE THREAD

**Issue by felixvonsamson** [felixvonsamson/Energetica#235]

**Comment by mglst** [comment]
Fixed? If so, close with comment "Fixed in #commit_id"

**Comment by felixvonsamson** [comment]
fixed in #7f098e33f4f98e71cb2301191999c1b08c567d19

**Comment by felixvonsamson** [comment]
fixed in #7f098e33f4f98e71cb2301191999c1b08c567d19
